# Generated by Django 3.2.21 on 2024-03-05 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20240305_0529'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saved', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saved',
            options={'ordering': ['-created_at'], 'verbose_name': 'Saved', 'verbose_name_plural': 'Saved'},
        ),
        migrations.AlterField(
            model_name='saved',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='saved',
            name='owner',
            field=models.ForeignKey(help_text='The user who saved the post', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='saved',
            name='post',
            field=models.ForeignKey(help_text='The post being saved', on_delete=django.db.models.deletion.CASCADE, related_name='saved', to='posts.post', verbose_name='Post'),
        ),
    ]
