# Generated by Django 3.2.21 on 2024-03-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0002_auto_20240305_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='email',
            field=models.CharField(blank=True, help_text='email of the user making the contact', max_length=150),
        ),
    ]
