# Generated by Django 3.2.21 on 2024-03-05 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contactform', '0003_contactform_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='email',
            field=models.CharField(blank=True, help_text='email of the user making the contact', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Contact User', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
