# Generated by Django 3.2.21 on 2024-03-05 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('followers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follower',
            options={'ordering': ['-created_at'], 'verbose_name': 'Follower', 'verbose_name_plural': 'Followers'},
        ),
        migrations.AlterField(
            model_name='follower',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='follower',
            name='followed',
            field=models.ForeignKey(help_text='The user who is being followed by another user', on_delete=django.db.models.deletion.CASCADE, related_name='followed', to=settings.AUTH_USER_MODEL, verbose_name='Followed'),
        ),
        migrations.AlterField(
            model_name='follower',
            name='owner',
            field=models.ForeignKey(help_text='The user who is following another user', on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='Follower'),
        ),
    ]
